title: PlatinumSrc
description: PlatinumSrc Game Engine
domain: platinumsrc.github.io
url: https://platinumsrc.github.io
baseurl: /
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
